### ISSUE TITLE
`TransferPolicy.sol` is locked to solidity `0.8.9`.

### ISSUE THREAD

**Issue by frenchypeanut** [limitbreakinc/creator-token-contracts#5]
I'm trying to import the contracts to another project which is locked to `pragma solidity 0.8.4;`.

All the libraries seem to be okay except one file:
https://github.com/limitbreakinc/creator-token-contracts/blob/fc541eec2f062cf26eab942e015db54b84dec834/contracts/utils/TransferPolicy.sol#L2

Which is the only file of the entire project locked to a specific solidity version, whereas the rest of the protocol is allowing solidity 0.8.4 or above.

It breaks the compilation on my part, unless I update the `TransferPolicy` file manually with `pragma solidity ^0.8.4;`.

It should probably be updated in the official repo.

**Comment by nathanglb** [comment]
Apologies!  We will get that fixed ASAP.

**Comment by nathanglb** [comment]
Fixed!  Update to version 1.1.2.
